version: "3"

tasks:
  default:
    - task: help

  help:
    desc: "List all tasks"
    silent: true
    cmds:
      - task --list-all

  generate-pre-commit-config:
    desc: "Generate .pre-commit-config.yaml file from .pre-commit-config.yaml.template"
    silent: true
    preconditions:
      - test -f .pre-commit-config.yaml.template
    generates:
      - .pre-commit-config.yaml
    env:
      PRE_COMMIT_ADDITIONAL_DEPENDENCIES:
        sh: echo "$(uv export --no-dev --no-hashes --no-header --frozen | while read line; do echo "          - $(echo ${line} | sed "s/^[[:space:]]*//")"; done)"
    cmds:
      - awk '{gsub(/\$PRE_COMMIT_ADDITIONAL_DEPENDENCIES/, ENVIRON["PRE_COMMIT_ADDITIONAL_DEPENDENCIES"]); print}' .pre-commit-config.yaml.template > .pre-commit-config.yaml   
      - echo "The .pre-commit-config.yaml file has been generated."

  update-pre-commit-config:
    desc: "Install or Update versions .pre-commit-config.yaml and uv update"
    cmds:
      - uv run pre-commit install
      - uv sync -U
      - task generate-pre-commit-config
      - uv run pre-commit autoupdate
      - echo "The pre-commit updated."

  lint:
    desc: "Run pre-commit run --all-files"
    preconditions:
      - test -f .pre-commit-config.yaml
    cmds:
      - uv run pre-commit run --all-files

  run-docker:
    desc: Run docker container
    cmds:
      - docker compose -f docker-compose.yaml --env-file ./.env up -d --build

  stop-docker:
    desc: Stop docker container
    cmds:
      - docker compose -f docker-compose.yaml --env-file ./.env down

  run:
    desc: Run local inside container
    cmds:
      - uv run python -m src

  coverage:
    desc: Run tests coverage
    cmds:
      - uv run pytest --cov=src --cov-report term-missing

  test:
    desc: Run tests
    cmds:
      - uv run pytest -x -n auto --dist loadscope

  retest:
    desc: Run restart tests
    cmds:
      - uv run pytest -lx --ff -n auto

  install:
    desc: Run init project
    cmds:
      - uv sync
      - uv add pydantic pydantic-settings
      - uv add --dev pre-commit ruff mypy vulture pytest pytest-cov pytest-mock pytest-asyncio pytest-randomly pytest-xdist hypothesis
      - chmod +x ./start.py
      - git init
      - git branch -M main
      - git add .
      - git commit -m "initial"
